name: CD

on:
  push:
    branches:
      - main

env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # env stuff
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: node - setup
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      # pnpm stuff
      - name: pnpm — install
        run: npm i pnpm@latest -g
      - name: pnpm - config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: pnpm - install
        run: pnpm install

      # build
      - name: build
        run: pnpm build

      - name: publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
